### ISSUE TITLE
400 bad request returned by UI

### ISSUE THREAD

**Issue by dancaescu** [sipcapture/homer#623]
Hi there,

Installed the docker version, today, from github (so all packages are at the latest version).

<img width="1498" alt="Screenshot 2023-12-20 at 3 55 01 PM" src="https://github.com/sipcapture/homer/assets/32689411/f4ffbfad-993e-4b95-a363-bd8a6f6f0a74">

On page:
/api/ds/query?ds_type=loki&requestId=Q100_1

Getting the following errors:

root@homer:~# docker logs -f qryn | grep "invalid request"
Couldn't execute script:
Expected [ or 'TAB' ] [@1:99](https://matrix.to/#/@1:99) encountered 'p "'.
)"b="heplify-server", src_ip=~".", dst_ip=~"."} | response=~".*" or type!="sip" |~ .* | regexp "Call-ID:\s+(?<callid>.+?
{"level":50,"time":1703094838129,"pid":27,"hostname":"6ad051fd9ad6","name":"qryn","reqId":"req-1j","err":"invalid request\nBad Request: invalid request\n at module.exports.transpile (/app/parser/transpiler.js:132:11)\n at scanFingerprints (/app/lib/db/clickhouse.js:243:29)\n at Object.handler (/app/lib/handlers/query_range.js:41:28)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","msg":"invalid request"}
Couldn't execute script:
Expected [ 'ESCSLASH', 'ESCAQUOTE', 'SQUOTE', 'QUOTE', 'CRLF', 'ESCAPE', 'REALPHA', 'DIGIT', or 'ONEWSP' ] [@1:99](https://matrix.to/#/@1:99) encountered '0.0.1| '. )"b="heplify-server", src_ip=~".*", dst_ip=~".*"} | response=~".*" or type!="sip" |~f1b7mm@127.0.0.1` | regexp "Call-ID:\s+(?<callid>.+?

<img width="1629" alt="Screenshot 2023-12-20 at 3 56 14 PM" src="https://github.com/sipcapture/homer/assets/32689411/69babe07-5cc8-4479-b2db-beade660b4e1">

HTTP request is answered with HTTP code 401 and the following body:
 {"results":{"A":{"error":"invalid request","errorSource":"","status":500}}}

**Comment by adubovikov** [comment]
please use the last homer 11
