### ISSUE TITLE
homer-app fails to start (code=exited, status=2)

### ISSUE THREAD

**Issue by daydone** [sipcapture/homer#626]
OS version: CentOS 7
heplify-server version: 1.59.5
homer-app version: 1.4.37
postgresql-12.service is running and listening on the correct ports, db is localhost.
heplify-server.service is running with no errors.
I have checked that I can access the DB with the homer_user login and password. stated in `/etc/heplify-server.toml`
I have validated that `/var/lib/pgsql/12/data/pg_hba.conf` has the correct md5 configuration from the install script.
When I check `journalctl -xe | grep homer-app` I get the bekow output:
`Jan 17 17:26:45 <hostname> homer-app[25618]: panic: failed to connect database
Jan 17 17:26:45 <hostname> homer-app[25618]: goroutine 1 [running]:
Jan 17 17:26:45 <hostname>homer-app[25618]: main.getConfigDBSession(0xcc0800)
Jan 17 17:26:45 <hostname> homer-app[25618]: /app/main.go:1187 +0xa65
Jan 17 17:26:45 <hostname> homer-app[25618]: main.main()
Jan 17 17:26:45 <hostname> homer-app[25618]: /app/main.go:236 +0xeb
Jan 17 17:26:45 <hostname>systemd[1]: homer-app.service: main process exited, code=exited, status=2/INVALIDARGUMENT`

In `tail /usr/local/homer/log/homer-app.log` I get the following error repeated:
`{"level":"error","msg":"pq: password authentication failed for user \"homer_user\"","time":"2024-01-17T17:28:48Z"}`

This installation has been working for over a year, no one has logged in or updated anything it just crashed 2 days ago and I am trying to recover the application. 
I have tried:
-Rebooting server
-resetting homer_user password for postgresql-12 
-using systemctl to restart/reload postgresql-12 and heplify-server/homer-app 

I am not sure what else to try as someone else installed this service originally 2 years ago. Any direction would be greatly appreciated!

**Comment by daydone** [comment]
Is there anyway this can get looked at?

**Comment by lmangani** [comment]
You could star the repository to get some priority. Most likely you have the wrong db authentication details somewhere, doublecheck the homer-app settings and it should start working.

> {"level":"error","msg":"pq: password authentication failed for user \"homer_user\"","time":"2024-01-17T17:28:48Z"}

**Comment by daydone** [comment]
@lmangani thank you for the response, I appreciate it. I have starred the repository, I have, checked that the `/etc/heplify-server.toml` is correctly configured for the database config. Is there some other conf file that is separate for homer-app? I see `/usr/local/homer/etc/webapp_config.json` but these are supposed to remain as values correct?

**Comment by adubovikov** [comment]
closed - reason - new Homer 11 release
