### ISSUE TITLE
Homer 7 Heplify-Server Service port 9060 shutdown

### ISSUE THREAD

**Issue by hesam476** [sipcapture/homer#647]
I have installed homer7 manually when i start heplify agent on my asterisk PBX like this "heplify -hs HOMER_Server:9060 -hn Srv-Test" service heplify-server port 9060 tcp and udp shutdown suddenly on homer server I attach server and client logs. please help 
Heplify Server Logs: 

![Heplify-Server-AfterTest](https://github.com/sipcapture/homer/assets/8292726/ac862624-01c1-4d03-bfd3-6010e3fd24de)
![Heplify-Server-BeforeTest](https://github.com/sipcapture/homer/assets/8292726/47a29afe-cb5d-4dec-aeef-48793f68ca54)

Heplify Clients Logs : 

![Heplify-Client-BeforeTest](https://github.com/sipcapture/homer/assets/8292726/d459ee8a-9e5e-42d8-a442-aa0e0cd1028f)
![Heplify-Client-BeforeTest-2](https://github.com/sipcapture/homer/assets/8292726/df3c4990-b3bc-4f42-ac6b-c77d323e2306)
![Heplify-Client-Log-AfterTest](https://github.com/sipcapture/homer/assets/8292726/f0bc3b18-4650-464c-9310-ab70bd25c5ee)

**Comment by hesam476** [comment]
when i start "./heplify -hs HOMER_SERVER:9060 -hn Srv-Test"  heplify-server service on port 9060  is shutdown 

![Heplify-Server-AfterTest-Ports](https://github.com/sipcapture/homer/assets/8292726/533d49b7-727a-4dc9-9538-1a9160fc038b)

and after the test script is stopped heplify-server serice on port 9060 is ok on HOMER Service 
![Heplify-Server-AfterTest-NTPLU](https://github.com/sipcapture/homer/assets/8292726/ddff8306-fbf9-4058-8e65-869e91d12aec)

**Comment by lmangani** [comment]
Does the same happen with fewer options? `./heplify -hs HOMER_SERVER:9060`

**Comment by hesam476** [comment]
yes this happen again with fewer options

**Comment by lmangani** [comment]
I don't see any errors. Make sure you include all the logs and any coredump if the process faults.

**Comment by hesam476** [comment]
Hi this is some logs from Homer Server /var/log/syslog: 

Jul  7 09:51:49 121-Homer systemd[1]: heplify-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul  7 09:51:49 121-Homer systemd[1]: heplify-server.service: Failed with result 'exit-code'.
Jul  7 09:51:59 121-Homer systemd[1]: heplify-server.service: Scheduled restart job, restart counter is at 238.
Jul  7 09:51:59 121-Homer systemd[1]: Stopped HEP Server & Switch in Go.
Jul  7 09:51:59 121-Homer systemd[1]: Started HEP Server & Switch in Go.
**Jul  7 09:52:05 121-Homer heplify-server[102948]: panic: runtime error: invalid memory address or nil pointer dereference**
**Jul  7 09:52:05 121-Homer heplify-server[102948]: #011panic: runtime error: invalid memory address or nil pointer dereference**
**Jul  7 09:52:05 121-Homer heplify-server[102948]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xb4 pc=0xb177bd]**
Jul  7 09:52:05 121-Homer heplify-server[102948]: goroutine 73 [running]:
Jul  7 09:52:05 121-Homer heplify-server[102948]: sync.(*Mutex).Lock(...)
Jul  7 09:52:05 121-Homer heplify-server[102948]: #011/usr/local/go/src/sync/mutex.go:74
Jul  7 09:52:05 121-Homer heplify-server[102948]: github.com/olivere/elastic.(*BulkProcessor).Flush(0x0, 0x6, 0xfc087b)
Jul  7 09:52:05 121-Homer heplify-server[102948]: #011/go/pkg/mod/github.com/olivere/elastic@v6.2.33+incompatible/bulk_processor.go:410 +0x2d
Jul  7 09:52:05 121-Homer heplify-server[102948]: github.com/sipcapture/heplify-server/remotelog.(*Elasticsearch).start.func1(0xc0000a20a0)
Jul  7 09:52:05 121-Homer heplify-server[102948]: #011/app/remotelog/elasticsearch.go:70 +0x42
Jul  7 09:52:05 121-Homer heplify-server[102948]: panic(0xe826e0, 0x17d8b70)
Jul  7 09:52:05 121-Homer heplify-server[102948]: #011/usr/local/go/src/runtime/panic.go:679 +0x1b2
Jul  7 09:52:05 121-Homer heplify-server[102948]: github.com/olivere/elastic.(*BulkProcessor).Add(...)
Jul  7 09:52:05 121-Homer heplify-server[102948]: #011/go/pkg/mod/github.com/olivere/elastic@v6.2.33+incompatible/bulk_processor.go:404
Jul  7 09:52:05 121-Homer heplify-server[102948]: github.com/sipcapture/heplify-server/remotelog.(*Elasticsearch).start(0xc0000a20a0, 0xc0000320c0)
Jul  7 09:52:05 121-Homer heplify-server[102948]: #011/app/remotelog/elasticsearch.go:85 +0x31d
Jul  7 09:52:05 121-Homer heplify-server[102948]: github.com/sipcapture/heplify-server/remotelog.(*Remotelog).Run.func1(0xc0000a20c0)
Jul  7 09:52:05 121-Homer heplify-server[102948]: #011/app/remotelog/remotelog.go:36 +0x3c
Jul  7 09:52:05 121-Homer heplify-server[102948]: created by github.com/sipcapture/heplify-server/remotelog.(*Remotelog).Run
Jul  7 09:52:05 121-Homer heplify-server[102948]: #011/app/remotelog/remotelog.go:35 +0x6d
Jul  7 09:52:05 121-Homer systemd[1]: heplify-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul  7 09:52:05 121-Homer systemd[1]: heplify-server.service: Failed with result 'exit-code'.
Jul  7 09:52:15 121-Homer systemd[1]: heplify-server.service: Scheduled restart job, restart counter is at 239.
Jul  7 09:52:15 121-Homer systemd[1]: Stopped HEP Server & Switch in Go.
Jul  7 09:52:15 121-Homer systemd[1]: Started HEP Server & Switch in Go.
Jul  7 09:53:26 121-Homer heplify-server[102958]: panic: runtime error: invalid memory address or nil pointer dereference
Jul  7 09:53:26 121-Homer heplify-server[102958]: #011panic: runtime error: invalid memory address or nil pointer dereference
Jul  7 09:53:26 121-Homer heplify-server[102958]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xb4 pc=0xb177bd]

**Comment by lmangani** [comment]
what are the specs of the system running heplify-server? this is definitely not normal

> Jul 7 09:53:26 121-Homer heplify-server[102958]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 7 09:53:26 121-Homer heplify-server[102958]: #011panic: runtime error: invalid memory address or nil pointer dereference
Jul 7 09:53:26 121-Homer heplify-server[102958]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xb4 pc=0xb177bd]

**Comment by hesam476** [comment]
OS: Debian 11 
Kernel: 5.10.209-2
heplify-server version: 1.59.6
homer-app version: 1.4.59
postgresql version: 13.14
Memory: 4GB - free 2.5GB
"I noticed that the server clock is 7 minutes behind the current time." I fix the time but issue not solved yet  what other specs should i check ?

**Comment by adubovikov** [comment]
closed - reason - new Homer 11 release
